# Overview

https://leetcode.com/problems/minimum-path-sum/editorial/

We have to find the minimum sum of numbers over a path from the top left to the bottom right of the given matrix

In [7]:
import numpy as np

from typing import List

In [66]:
class Solution:
    def get_min_path_sum(self, grid: np.array) -> int:
        '''
        dp[i][j] = dp[i][j] + min(dp[i+1,j], dp[i,j+1])

input:
        [
            [1,3,1],
            [1,5,1],
            [4,2,1],
        ]

dp:
        [
            [7,6,3],
            [8,7,2],
            [7,3,1],
        ]
        [
            [N,2,1],
        ]
        '''
        m,n = grid.shape
        dp = np.zeros(n)
        for i in reversed(range(m)):
            for j in reversed(range(n)): # column
                # dp[i][j] = dp[i][j] + min(dp[i+1][j], dp[i][j+1])
#                 print((i,j))
                if i < (m-1) and j < (n-1):
                    dp[j] = grid[i][j] + min(dp[j], dp[j+1])
                elif i == (m-1) and j < (n-1):
                    dp[j] = grid[i][j] + dp[j+1]
                elif j == (n-1) and i < (m-1):
                    dp[j] = grid[i][j] + dp[j]
                else:
                    dp[j] = grid[i][j]
            
            print(f"--- {i} ---")
            print(dp)

        return int(dp[0])
    
    
    
    
res1 = Solution().get_min_path_sum(np.array(
    [
        [1,3,1],
        [1,5,1],
        [4,2,1],
    ]))
assert res1 == 7, f"{res1} != 7"

--- 2 ---
[7. 3. 1.]
--- 1 ---
[8. 7. 2.]
--- 0 ---
[7. 6. 3.]


In [73]:
class Solution:
    def get_min_path_sum(self, grid: np.array) -> int:
        '''
        dp[i][j] = dp[i][j] + min(dp[i+1,j], dp[i,j+1])

input:
        [
            [1,3,1],
            [1,5,1],
            [4,2,1],
        ]

dp:
        [
            [7,6,3],
            [8,7,2],
            [7,3,1],
        ]
        '''
        m,n = grid.shape
        for i in reversed(range(m)):
            for j in reversed(range(n)): # column
                # dp[i][j] = dp[i][j] + min(dp[i+1][j], dp[i][j+1])
#                 print((i,j))
                if i < (m-1) and j < (n-1):
                    grid[i][j] = grid[i][j] + min(grid[i+1][j], grid[i][j+1])
                elif i == (m-1) and j < (n-1):
                    grid[i][j] = grid[i][j] + grid[i][j+1]
                elif j == (n-1) and i < (m-1):
                    grid[i][j] = grid[i][j] + grid[i+1][j]
            
                print(f"({i},{j}) -> {grid[i][j]}")
            
            print(f"---")

        return int(grid[0][0])
    
    
    
    
res1 = Solution().get_min_path_sum(np.array(
    [
        [1,3,1],
        [1,5,1],
        [4,2,1],
    ]))
assert res1 == 7, f"{res1} != 7"

(2,2) -> 1
(2,1) -> 3
(2,0) -> 7
---
(1,2) -> 2
(1,1) -> 7
(1,0) -> 8
---
(0,2) -> 3
(0,1) -> 6
(0,0) -> 7
---


3


AssertionError: None != 7