In [1]:
import numpy as np

In [2]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [3]:
a2 = a[np.newaxis, :]
a2

array([[0, 1, 2, 3, 4, 5]])

In [4]:
a2.shape

(1, 6)

In [5]:
a.shape

(6,)

In [8]:
a[np.newaxis, np.newaxis, :]

array([[[0, 1, 2, 3, 4, 5]]])

In [9]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [10]:
a[1]

2